### ISSUE TITLE
Generating Duplicates

### ISSUE THREAD

**Issue by waitforitx** [LipConqueror/golips_art_engine#1]
Hello,

First of all, good job on the code!
I'm having issues using your generator - it generates duplicates. I checked the metadata and DNA is the same for the duplicates.
I'm using lots of traits for conflicts - I'm not sure if this could be the issue.
I actually thought it might be because I was using multiple processes/threads, but I get duplicates even with only 1 process.

Am I missing a setting somewhere?

**Comment by LipConqueror** [comment]
> Hello,
> 
> First of all, good job on the code! I'm having issues using your generator - it generates duplicates. I checked the metadata and DNA is the same for the duplicates. I'm using lots of traits for conflicts - I'm not sure if this could be the issue. I actually thought it might be because I was using multiple processes/threads, but I get duplicates even with only 1 process.
> 
> Am I missing a setting somewhere?

I check the code, it's a dumb mistake I made when checking the dna, I'll fix it soon

**Comment by LipConqueror** [comment]
@waitforitx 
Fixed on v0.0.4
Please let us know if there is any other problems, and if you don't mind, after your nft is published, inform us the official link so we can add it in our readme 😁
