### ISSUE TITLE
是否能简单介绍一下特定组合的使用方法？

### ISSUE THREAD

**Issue by huangyuzhang** [LipConqueror/golips_art_engine#2]
你好，感谢提供如此简洁方便的工具，但是对于特定组合的使用能否简单介绍一下？比如config的设置和文件名称的规则。
谢谢！

**Comment by LipConqueror** [comment]
> 你好，感谢提供如此简洁方便的工具，但是对于特定组合的使用能否简单介绍一下？比如config的设置和文件名称的规则。
> 谢谢！

我们更新了一下readme，即主页的说明
请看一下是否能够理解，如果还有疑问，欢迎再次留言

**Comment by huangyuzhang** [comment]
非常感谢！原来直接用对应的名称作为子目录就行了，很方便！
Cheers!
